Theme:
	name: Leslie
	power: Hexo
	
rss: /atom.xml
pjax: true
lazyload: /img/load.gif
	
Header:
	home: /
	essay: /categories/éšç¬”/
	note: /categories/ç¬”è®°/
	movie: /categories/ç”µå½±/
	# game: /categories/æ¸¸æˆ/
	archives: /archives
	friends: /about/
	# photo: /photo
	search: /search/

Website:
	name: ğŸŒ¿æ‚¬é“ƒæœ¨.
	logo: /img/logo.jpg
	description: plus I'll see you there utmost definitely!.
	
Author:
	name: æ‚¬é“ƒæœ¨.
	intro: plus I'll see you there utmost definitely!
	avastar: /img/faces.jpeg
	
Contact: 
	github: https://github.com/lorre0322
	wechat: Lorre_0322
	music: https://music.163.com/#/user/home?id=480021387
	mail: lorre0322@foxmail.com
	# tencent: 693739563
	# bilibili:  https://space.bilibili.com/35788350
	
CopyRight:
  License: CC BY-NC-SA 3.0 CN
  copyright_since: 'Â© 2018 - 2020'

